import type { Product, Language, Order } from './types';

export const CATEGORIES: string[] = [
    'All', 'Electronics', 'Clothing', 'Groceries', 'Mobile Phones', 'Beauty & Health'
];

export const PRICE_RANGES = [
    { key: 'all', labelKey: 'all_prices' },
    { key: '0-500', label: 'SLL 0 - 500' },
    { key: '500-1000', label: 'SLL 500 - 1000' },
    { key: '1000+', label: 'SLL 1000+' }
];

export const RATING_FILTERS = [
    { key: 0, labelKey: 'all_ratings' },
    { key: 4, labelKey: 'four_stars_up' },
    { key: 3, labelKey: 'three_stars_up' }
];

export const MOCK_PRODUCTS: Product[] = [
    { 
        id: 1, 
        name: 'Premium Wireless Headphones', 
        description: 'Experience immersive sound with these noise-cancelling headphones. Available in multiple colors.', 
        price: 850,
        originalPrice: 1200,
        stock: 8,
        saleEndDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // Ends in 2 days
        images: ['https://picsum.photos/seed/hp/400/400', 'https://picsum.photos/seed/hp2/400/400', 'https://picsum.photos/seed/hp3/400/400'], 
        category: 'Electronics', 
        rating: 4.8, 
        reviewsCount: 2, 
        vendor: 'TechSavvy SL', 
        sellerId: 'system',
        variants: [
            {
                type: 'Color',
                options: [
                    { name: 'Black', price: 850, stock: 3 },
                    { name: 'White', price: 850, stock: 5 },
                    { name: 'Blue', price: 900, stock: 2 },
                ]
            }
        ],
        reviews: [
            { author: 'Amara', rating: 5, comment: 'Best headphones I have ever owned! The noise cancellation is superb.', date: '2023-10-15' },
            { author: 'Isata', rating: 4, comment: 'Great sound quality and very comfortable to wear for long hours.', date: '2023-10-12' },
        ]
    },
    { 
        id: 2, 
        name: 'Men\'s Cotton T-Shirt', 
        description: 'Comfortable and stylish t-shirt made from 100% pure cotton.', 
        price: 150,
        stock: 50,
        images: ['https://picsum.photos/seed/shirt/400/400'], 
        category: 'Clothing', 
        rating: 4.5, 
        reviewsCount: 1, 
        vendor: 'Freetown Fashion', 
        sellerId: 'system',
        variants: [
            {
                type: 'Color',
                options: [
                    { name: 'White', price: 150, stock: 20 },
                    { name: 'Black', price: 150, stock: 25 },
                ]
            },
            {
                type: 'Size',
                options: [
                    { name: 'M', price: 150, stock: 15 },
                    { name: 'L', price: 150, stock: 20 },
                    { name: 'XL', price: 160, stock: 10 },
                ]
            }
        ],
        reviews: [
             { author: 'John', rating: 5, comment: 'Perfect fit and very soft material. Will buy again!', date: '2023-09-20' },
        ]
    },
    { id: 3, name: 'Organic Brown Rice (5kg)', description: 'Healthy and nutritious organic brown rice for your family.', price: 250, stock: 100, images: ['https://picsum.photos/seed/rice/400/400'], category: 'Groceries', rating: 4.9, reviewsCount: 88, vendor: 'Salone Fresh Mart', sellerId: 'system' },
    { 
        id: 4, 
        name: 'Latest Smartphone Model X', 
        description: 'A powerful smartphone with a stunning display and long battery life.', 
        price: 3900, 
        originalPrice: 4500,
        stock: 25,
        saleEndDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(), // Ends in 1 day 3 hours
        images: ['https://picsum.photos/seed/phone/400/400', 'https://picsum.photos/seed/phone2/400/400'], 
        category: 'Mobile Phones', 
        rating: 4.7, 
        reviewsCount: 190, 
        vendor: 'Mobile Hub', 
        sellerId: 'system' 
    },
    { id: 5, name: 'Shea Butter Body Lotion', description: 'Nourish your skin with this natural shea butter body lotion.', price: 95, stock: 80, images: ['https://picsum.photos/seed/lotion/400/400'], category: 'Beauty & Health', rating: 4.9, reviewsCount: 310, vendor: 'Mama Salone Beauty', sellerId: 'system' },
    { id: 6, name: 'Bluetooth Speaker Portable', description: 'Take your music anywhere with this compact and powerful bluetooth speaker.', price: 450, stock: 40, images: ['https://picsum.photos/seed/speaker/400/400'], category: 'Electronics', rating: 4.6, reviewsCount: 155, vendor: 'TechSavvy SL', sellerId: 'system' },
    { 
        id: 7, 
        name: 'Women\'s Ankara Print Dress', 
        description: 'Vibrant and elegant Ankara dress for all occasions.', 
        price: 320,
        originalPrice: 400,
        stock: 5,
        saleEndDate: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(), // Ends in 5 hours
        images: ['https://picsum.photos/seed/dress/400/400', 'https://picsum.photos/seed/dress2/400/400'], 
        category: 'Clothing', 
        rating: 4.8, 
        reviewsCount: 95, 
        vendor: 'Freetown Fashion', 
        sellerId: 'system'
    },
    { id: 8, name: 'Groundnut Paste (500g)', description: 'Locally made, delicious groundnut paste. Perfect for sauces.', price: 60, stock: 200, images: ['https://picsum.photos/seed/paste/400/400'], category: 'Groceries', rating: 5.0, reviewsCount: 200, vendor: 'Salone Fresh Mart', sellerId: 'system' }
];

export const MOCK_ORDERS: Order[] = [
    {
        id: 'SK-1700000000000',
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
        buyerInfo: {
            fullName: 'Demo User',
            phoneNumber: '077-123-456',
            deliveryAddress: '123 Main St, Freetown'
        },
        items: [
            {
                product: MOCK_PRODUCTS.find(p => p.id === 1)!,
                quantity: 1,
                variant: { Color: 'Black' },
                cartItemId: '1-Color-Black'
            },
            {
                product: MOCK_PRODUCTS.find(p => p.id === 3)!,
                quantity: 2,
                cartItemId: '3-none'
            }
        ],
        total: MOCK_PRODUCTS.find(p => p.id === 1)!.price * 1 + MOCK_PRODUCTS.find(p => p.id === 3)!.price * 2,
        buyerId: 'buyer-demo-1'
    },
    {
        id: 'SK-1700000000500',
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
        buyerInfo: {
            fullName: 'Demo User',
            phoneNumber: '077-123-456',
            deliveryAddress: '123 Main St, Freetown'
        },
        items: [
            {
                product: MOCK_PRODUCTS.find(p => p.id === 5)!,
                quantity: 1,
                cartItemId: '5-none'
            }
        ],
        total: MOCK_PRODUCTS.find(p => p.id === 5)!.price * 1,
        buyerId: 'buyer-demo-1'
    }
];

export const LOCAL_STORAGE_KEYS = {
    SELLERS: 'salonekart_sellers',
    BUYERS: 'salonekart_buyers',
    PRODUCTS: 'sellerProducts',
    ORDERS: 'salonekart_orders',
    THEME: 'theme',
};

export const SESSION_STORAGE_KEYS = {
    SELLER_ID: 'currentSellerId',
    BUYER_ID: 'currentBuyerId',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
    en: {
        'search_placeholder': 'Search for products...',
        'categories': 'Categories',
        'all': 'All',
        'electronics': 'Electronics',
        'clothing': 'Clothing',
        'groceries': 'Groceries',
        'mobile_phones': 'Mobile Phones',
        'beauty_health': 'Beauty & Health',
        'add_to_cart': 'Add to Cart',
        'reviews': 'reviews',
        'vendor_ai_assistant': 'Vendor AI Assistant',
        'ai_description': 'Generate a compelling product description with AI!',
        'product_keywords': 'Enter product keywords (e.g., "red leather handbag")',
        'generate_description': 'Generate Description',
        'generating': 'Generating...',
        'shopping_cart': 'Shopping Cart',
        'empty_cart': 'Your cart is empty.',
        'subtotal': 'Subtotal',
        'proceed_to_checkout': 'Proceed to Checkout',
        'checkout': 'Checkout',
        'delivery_details': 'Delivery Details',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'delivery_address': 'Delivery Address',
        'payment_method': 'Payment Method',
        'cash_on_delivery': 'Cash on Delivery',
        'orange_money': 'Orange Money',
        'africell_money': 'Africell Money',
        'syllogy_mobile_money': 'Syllogy Mobile Money',
        'natcom_top_up': 'NatCom Top Up',
        'place_order': 'Place Order',
        'close': 'Close',
        'english': 'English',
        'krio': 'Krio',
        'sort_by': 'Sort by',
        'sort_default': 'Default',
        'sort_price_asc': 'Price: Low to High',
        'sort_price_desc': 'Price: High to Low',
        'seller_dashboard': 'Seller Dashboard',
        'add_new_product': 'Add New Product',
        'product_name': 'Product Name',
        'product_description': 'Product Description',
        'product_price': 'Price (SLL)',
        'product_category': 'Category',
        'product_image': 'Product Image(s)',
        'upload_image': 'Upload Image(s)',
        'image_preview': 'Image Previews',
        'add_product': 'Add Product',
        'my_products': 'My Products',
        'my_profile': 'My Profile',
        'order_history': 'Order History',
        'no_products_added': 'You have not added any products yet.',
        'no_orders_yet': 'You have no orders yet.',
        'order_id': 'Order ID',
        'date': 'Date',
        'total': 'Total',
        'buyer_information': 'Buyer Information',
        'items_in_order': 'Items in this Order',
        'fill_all_fields': 'Please fill out all fields and upload at least one image.',
        'max_images_error': 'You can upload a maximum of 5 images.',
        'seller_login_signup': 'Seller Login / Sign Up',
        'logout': 'Logout',
        'login': 'Login',
        'signup': 'Sign Up',
        'email': 'Email Address',
        'store_name': 'Store Name',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'login_prompt': 'Already have an account?',
        'signup_prompt': 'Don\'t have an account?',
        'login_error': 'Invalid email or password.',
        'signup_email_exists': 'An account with this email already exists.',
        'signup_password_mismatch': 'Passwords do not match.',
        'signup_invalid_email': 'Please enter a valid email address.',
        'signup_password_weak': 'Password must be at least 8 characters long, contain at least one number, and one special character (!@#$%).',
        'auth_storage_error': 'Could not access local storage. Please ensure it is enabled in your browser.',
        'update_profile': 'Update Profile',
        'profile_updated_success': 'Your profile has been updated successfully!',
        'profile_update_error': 'Failed to update profile. Please try again.',
        'email_in_use_error': 'This email is already in use by another account.',
        'forgot_password': 'Forgot Password?',
        'reset_password': 'Reset Password',
        'reset_password_prompt': "Enter your email and we'll send you a link to reset your password.",
        'send_reset_link': 'Send Reset Link',
        'back_to_login': 'Back to Login',
        'reset_link_sent': 'If an account with that email exists, a password reset link has been sent.',
        'store_name_required': 'Store name is required.',
        'customer_service': 'Customer Service',
        'help_center': 'Help Center',
        'how_to_buy': 'How to Buy',
        'track_your_order': 'Track Your Order',
        'track_order': 'Track Order',
        'track_order_placeholder': 'Enter your Order ID (e.g., SK-123...)',
        'track_order_button': 'Track',
        'invalid_order_id_format': 'Please enter a valid Order ID (e.g., SK-123456789).',
        'order_not_found_error': 'Order not found. Please check the ID and try again.',
        'returns_refunds': 'Returns & Refunds',
        'about_salonekart': 'About SaloneKart',
        'about_us': 'About Us',
        'careers': 'Careers',
        'terms_conditions': 'Terms & Conditions',
        'privacy_policy': 'Privacy Policy',
        'sell_on_salonekart': 'Sell on SaloneKart',
        'start_selling': 'Start Selling',
        'vendor_hub': 'Vendor Hub',
        'success_stories': 'Success Stories',
        'connect_with_us': 'Connect with Us',
        'chatbot_greeting': "Hi! I'm Kadi, your SaloneKart assistant. How can I help you today?",
        'chatbot_error': "Sorry, I'm having a little trouble connecting right now. Please try again later.",
        'chatbot_placeholder': 'Ask about delivery, payment...',
        'chatbot_typing': 'Kadi is typing...',
        'chatbot_title': 'Ask Kadi',
        'buyer': 'Buyer',
        'seller': 'Seller',
        'login_signup': 'Login / Sign Up',
        'my_account': 'My Account',
        'buyer_dashboard': 'Buyer Dashboard',
        'dashboard': 'Dashboard',
        'top_selling_products': 'Top Selling Products',
        'units_sold': 'Units Sold',
        'stock': 'Stock',
        'update': 'Update',
        'stock_updated': 'Updated!',
        'edit_product_details': 'Edit Product Details',
        'compare': 'Compare',
        'remove_from_compare': 'Remove from Compare',
        'compare_items': 'Compare Items',
        'clear_all': 'Clear All',
        'comparison_limit_error': 'You can compare a maximum of 4 products.',
        'product_comparison': 'Product Comparison',
        'remove': 'Remove',
        'price': 'Price',
        'rating': 'Rating',
        'stock_status': 'Stock Status',
        'in_stock': 'In Stock',
        'low_stock': 'Low Stock',
        'out_of_stock': 'Out of Stock',
        'price_range': 'Price Range',
        'all_prices': 'All Prices',
        'all_ratings': 'All Ratings',
        'four_stars_up': '4 Stars & Up',
        'three_stars_up': '3 Stars & Up',
        'wishlist': 'Wishlist',
        'my_wishlist': 'My Wishlist',
        'add_to_wishlist': 'Add to Wishlist',
        'remove_from_wishlist': 'Remove from Wishlist',
        'empty_wishlist': 'Your wishlist is empty.',
        'empty_wishlist_prompt': 'Tap the heart on products to save them for later.',
    },
    krio: {
        'search_placeholder': 'Luk fo tin dɛn...',
        'categories': 'Kayn Tin Dɛn',
        'all': 'Ɔl',
        'electronics': 'Ɛlɛktrɔnik Tin Dɛn',
        'clothing': ' क्लoth',
        'groceries': 'It Tin Dɛn',
        'mobile_phones': 'Mobayl Fon Dɛn',
        'beauty_health': 'Bɔdi Wɛlnes',
        'add_to_cart': 'Put Insay Kat',
        'reviews': ' रिव्यूस',
        'vendor_ai_assistant': 'Vɛnda AI Asist',
        'ai_description': 'Mek AI rayt fayn diskripshɔn fɔ yu prodɔkt!',
        'product_keywords': 'Put di prodɔkt in kiwɔd (ɛg "rɛd lɛda anbag")',
        'generate_description': 'Mek Diskripshɔn',
        'generating': 'I de mek am...',
        'shopping_cart': 'Shɔpin Kat',
        'empty_cart': 'Yu kat ɛmti.',
        'subtotal': 'Subtotal',
        'proceed_to_checkout': 'Go fɔ Pe',
        'checkout': 'Pement',
        'delivery_details': 'Usay fɔ Kɛr Am Go',
        'full_name': 'Yu Ful Nem',
        'phone_number': 'Fon Nɔmba',
        'delivery_address': 'Adres fɔ Diliva',
        'payment_method': 'Aw fɔ Pe',
        'cash_on_delivery': 'Pe we dɛn Bring am',
        'orange_money': 'Orange Mɔni',
        'africell_money': 'Africell Mɔni',
        'syllogy_mobile_money': 'Syllogy Mobayl Mɔni',
        'natcom_top_up': 'NatCom Top Ɔp',
        'place_order': 'Mek di Ɔda',
        'close': 'Klɔs',
        'english': 'Inglish',
        'krio': 'Krio',
        'sort_by': 'Sɔt bay',
        'sort_default': 'Normal',
        'sort_price_asc': 'Prayz: Smol to Big',
        'sort_price_desc': 'Prayz: Big to Smol',
        'seller_dashboard': 'Sɛla Dashbɔd',
        'add_new_product': 'Put Nyu Prodɔkt',
        'product_name': 'Prodɔkt Nem',
        'product_description': 'Diskripshɔn fɔ di Prodɔkt',
        'product_price': 'Prayz (SLL)',
        'product_category': 'Kayn Tin',
        'product_image': 'Prodɔkt Pikchɔ(dɛn)',
        'upload_image': 'Put Pikchɔ(dɛn)',
        'image_preview': 'Pikchɔ Privyu Dɛn',
        'add_product': 'Put di Prodɔkt',
        'my_products': 'Mi Prodɔkt Dɛn',
        'my_profile': 'Mi Profayl',
        'order_history': 'Ɔda Istri',
        'no_products_added': 'Yu nɔ put ɛni prodɔkt yet.',
        'no_orders_yet': 'Yu nɔ gɛt ɔda yet.',
        'order_id': 'Ɔda ID',
        'date': 'Det',
        'total': 'Total',
        'buyer_information': 'Infɔmeshɔn fɔ di Pɔsin we Bay',
        'items_in_order': 'Tin dɛn insay dis Ɔda',
        'fill_all_fields': 'Plis, rayt ɔl di tin dɛn na di bɔks dɛn ɛn put at list wan pikchɔ.',
        'max_images_error': 'Yu go ebul fɔ ɔplod nɔmɔ 5 pikchɔ.',
        'seller_login_signup': 'Sɛla Lɔgin / Sain Ɔp',
        'logout': 'Lɔg Aut',
        'login': 'Lɔgin',
        'signup': 'Sain Ɔp',
        'email': 'Imel Adrɛs',
        'store_name': 'Sto Nem',
        'password': 'Paswɔd',
        'confirm_password': 'Rayt di Paswɔd Bak',
        'login_prompt': 'Yu gɛt akant ɔlrɛdi?',
        'signup_prompt': 'Yu nɔ gɛt akant?',
        'login_error': 'Di imel ɔ paswɔd nɔ kɔrɛkt.',
        'signup_email_exists': 'Sɔmbɔdi de yuz dis imel ɔlrɛdi.',
        'signup_password_mismatch': 'Di paswɔd dɛn nɔ mach.',
        'signup_invalid_email': 'Plis, rayt kɔrɛkt imel adrɛs.',
        'signup_password_weak': 'Di paswɔd fɔ pas 8 karakta, ɛn i fɔ gɛt nɔmba ɛn spɛshal mak insay (!@#$%).',
        'auth_storage_error': 'Wi nɔ ebul fɔ akses lokal stɔrej. Plis, mek shɔ se i de wok na yu brawza.',
        'update_profile': 'Apdet Profayl',
        'profile_updated_success': 'Yu profayl dɔn apdet!',
        'profile_update_error': 'Wi nɔ ebul fɔ apdet yu profayl. Plis, tray bak.',
        'email_in_use_error': 'Sɔmbɔdi ɔlrɛdi de yuz dis imel.',
        'forgot_password': 'Yu Fɔgɛt di Paswɔd?',
        'reset_password': 'Chenj Paswɔd',
        'reset_password_prompt': 'Rayt yu imel ɛn wi go sɛn yu link fɔ chenj yu paswɔd.',
        'send_reset_link': 'Sɛn di Link',
        'back_to_login': 'Go Bak fɔ Lɔgin',
        'reset_link_sent': 'If akant de wit da imel de, wi dɔn sɛn link fɔ chenj di paswɔd.',
        'store_name_required': 'Sto nem nid fɔ de.',
        'customer_service': 'Kɔstɔma Sevis',
        'help_center': 'Hɛp Sɛnta',
        'how_to_buy': 'Aw fɔ Bay',
        'track_your_order': 'Trak Yu Ɔda',
        'track_order': 'Trak Ɔda',
        'track_order_placeholder': 'Put yu Ɔda ID (ɛg, SK-123...)',
        'track_order_button': 'Trak',
        'invalid_order_id_format': 'Plis, rayt kɔrɛkt Ɔda ID (ɛg, SK-123456789).',
        'order_not_found_error': 'Wi nɔ si di ɔda. Plis, chɛk di ID ɛn tray bak.',
        'returns_refunds': 'Ritɔn & Rifɔnd',
        'about_salonekart': 'Bɔt SaloneKart',
        'about_us': 'Bɔt Wi',
        'careers': 'Wak',
        'terms_conditions': 'Tɛm & Kɔndishɔn',
        'privacy_policy': 'Prayvesi Pɔlisi',
        'sell_on_salonekart': 'Sɛl na SaloneKart',
        'start_selling': 'Stat fɔ Sɛl',
        'vendor_hub': 'Vɛnda Hɔb',
        'success_stories': 'Sɔksɛs Stori Dɛn',
        'connect_with_us': 'Kɔnɛkt Wit Wi',
        'chatbot_greeting': "Kushe! Na mi Kadi, yu SaloneKart asistant. Aw a go ɛp yu tide?",
        'chatbot_error': "Sɔri, a nɔ de ebul fɔ kɔnɛkt naw naw. Plis tray bak smɔl tɛm.",
        'chatbot_placeholder': 'Aks bɔt dilivari, pement...',
        'chatbot_typing': 'Kadi de rayt...',
        'chatbot_title': 'Aks Kadi',
        'buyer': 'Baya',
        'seller': 'Sɛla',
        'login_signup': 'Lɔgin / Sain Ɔp',
        'my_account': 'Mi Akant',
        'buyer_dashboard': 'Baya Dashbɔd',
        'dashboard': 'Dashbɔd',
        'top_selling_products': 'Prodɔkt dɛn we de Sɛl Pas ɔl',
        'units_sold': 'Yunit dɛn we dɛn dɔn sɛl',
        'stock': 'Stɔk',
        'update': 'Apdet',
        'stock_updated': 'Apdet!',
        'edit_product_details': 'Chenj Prodɔkt Ditels',
        'compare': 'Kɔmpia',
        'remove_from_compare': 'Kɔmɔt am na Kɔmpia',
        'compare_items': 'Kɔmpia di Tin Dɛn',
        'clear_all': 'Klia Ɔl',
        'comparison_limit_error': 'Yu go ebul fɔ kɔmpia nɔmɔ 4 tin.',
        'product_comparison': 'Kɔmpia Prodɔkt Dɛn',
        'remove': 'Kɔmɔt',
        'price': 'Prayz',
        'rating': 'Rɛtin',
        'stock_status': 'Stɔk Stetɔs',
        'in_stock': 'I De',
        'low_stock': 'I de pas',
        'out_of_stock': 'I dɔn dɔn',
        'price_range': 'Prayz Renj',
        'all_prices': 'Ɔl di Prayz dɛn',
        'all_ratings': 'Ɔl di Rɛtin dɛn',
        'four_stars_up': '4 Sta ɛn Ɔp',
        'three_stars_up': '3 Sta ɛn Ɔp',
        'wishlist': 'Wishlist',
        'my_wishlist': 'Mi Wishlist',
        'add_to_wishlist': 'Put na Wishlist',
        'remove_from_wishlist': 'Kɔmɔt na Wishlist',
        'empty_wishlist': 'Yu wishlist ɛmti.',
        'empty_wishlist_prompt': 'Prɛs di at-mak na di prodɔkt fɔ sev am fɔ let tɛm.',
    }
};